language: go
env:
 - GO111MODULE=on
#services:
# - docker
script: 
 - go install github.com/paypal/hera/mux github.com/paypal/hera/worker/mysqlworker github.com/paypal/hera/worker/oracleworker
 - go test github.com/paypal/hera/tests/unittest/coordinator_basic
 - pwd
 - $GOPATH/src/github.com/paypal/hera/tests/unittest/testall.sh
 - mvn install -f client/java/jdbc/pom.xml -Dmaven.test.skip=true
